// scripts/check-hygiene.mjs: the em dash and model-attribution checks that
// run in CI and from `npm run hygiene`. Em dashes are written as \u2014 so this
// file passes its own check.
import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { findEmDashes, findAttribution, findBodyProblems } from '../scripts/check-hygiene.mjs';

const D = '\u2014';
const script = fileURLToPath(new URL('../scripts/check-hygiene.mjs', import.meta.url));

test('findEmDashes reports added lines only, with file and new line number', () => {
  const diff = [
    'diff --git a/CHANGELOG.md b/CHANGELOG.md',
    '--- a/CHANGELOG.md',
    '+++ b/CHANGELOG.md',
    '@@ -3,0 +4,2 @@',
    `+### Added ${D} tools`,
    '+plain line',
    '@@ -10 +12 @@',
    '-old line',
    `+new ${D} line`,
  ].join('\n');
  assert.deepEqual(findEmDashes(diff), [
    { file: 'CHANGELOG.md', line: 4, text: `### Added ${D} tools` },
    { file: 'CHANGELOG.md', line: 12, text: `new ${D} line` },
  ]);
});

test('findEmDashes passes a reworded line that already had an em dash', () => {
  const diff = [
    '+++ b/README.md', '@@ -5 +5 @@', `-old wording ${D} kept`, `+new wording ${D} kept`,
    '@@ -9 +9 @@', `-one ${D} here`, `+one ${D} here ${D} and a new one`,
  ].join('\n');
  assert.deepEqual(findEmDashes(diff), [
    { file: 'README.md', line: 9, text: `one ${D} here ${D} and a new one` },
  ]);
});

test('findEmDashes counts context lines toward the new-file line number', () => {
  const diff = [
    'diff --git a/a.md b/a.md', '--- a/a.md', '+++ b/a.md', '@@ -10,2 +10,3 @@',
    ' context', `+text ${D} value`, ' more context',
  ].join('\n');
  assert.deepEqual(findEmDashes(diff), [{ file: 'a.md', line: 11, text: `text ${D} value` }]);
});

test('findEmDashes reads --- and +++ inside a hunk as content, not headers', () => {
  // A removed SQL comment `-- old` arrives as `--- old`; an added `++ x` as `+++ x`.
  const diff = [
    'diff --git a/q.sql b/q.sql', '--- a/q.sql', '+++ b/q.sql', '@@ -1,2 +1,2 @@',
    `--- old ${D} note`, `+-- new ${D} note`, '-x', '+++ still q.sql',
  ].join('\n');
  assert.deepEqual(findEmDashes(diff), []);
  const added = diff + `\n@@ -9,0 +9 @@\n+new ${D} here`;
  assert.deepEqual(findEmDashes(added), [{ file: 'q.sql', line: 9, text: `new ${D} here` }]);
});

test('findEmDashes skips lockfiles and deleted files, and passes an en dash or hyphen', () => {
  const diff = [
    'diff --git a/package-lock.json b/package-lock.json',
    '--- a/package-lock.json', '+++ b/package-lock.json', '@@ -1 +1 @@', `+"x ${D} y"`,
    'diff --git a/gone.md b/gone.md', '--- a/gone.md', '+++ /dev/null', '@@ -1 +0,0 @@', `-old ${D}`,
    'diff --git a/docs/a.md b/docs/a.md',
    '--- a/docs/a.md', '+++ b/docs/a.md', '@@ -0,0 +1,2 @@', '+range 1\u20132', '+a - b',
  ].join('\n');
  assert.deepEqual(findEmDashes(diff), []);
});

test('findAttribution flags a model author or committer', () => {
  assert.deepEqual(findAttribution({ authorName: 'Claude', authorEmail: 'noreply@anthropic.com' }),
    ['author is Claude <noreply@anthropic.com>']);
  assert.equal(findAttribution({ committerName: 'x', committerEmail: 'bot@anthropic.com' }).length, 1);
});

test('findAttribution flags model identities from every vendor, not only one', () => {
  const identities = [
    ['GPT', 'bot@openai.com'],
    ['ChatGPT Codex', 'codex@example.com'],
    ['Codex', 'x@openai.com'],
    ['Copilot', '198982749+Copilot@users.noreply.github.com'],
    ['copilot-swe-agent[bot]', '198982749+copilot-swe-agent[bot]@users.noreply.github.com'],
    ['gemini-code-assist[bot]', '176961590+gemini-code-assist[bot]@users.noreply.github.com'],
    ['Claude Opus 5.5', 'noreply@example.com'],
  ];
  for (const [authorName, authorEmail] of identities) {
    assert.ok(findAttribution({ authorName, authorEmail }).length > 0, `${authorName} <${authorEmail}>`);
  }
});

test('findAttribution flags other vendors\' trailers, generator lines and model ids', () => {
  for (const message of [
    'fix\n\nCo-authored-by: Copilot <198982749+Copilot@users.noreply.github.com>',
    'fix\n\nCo-Authored-By: ChatGPT <noreply@openai.com>',
    'fix\n\nCo-authored-by: gemini-code-assist[bot] <x@users.noreply.github.com>',
    'fix\n\nhttps://claude.ai/code/session_01ABC',
    'Generated with Codex',
    'Generated by Gemini',
    'written with gpt-5.1-codex',
    'drafted by gemini-2.5-pro',
  ]) {
    assert.ok(findAttribution({ message }).length > 0, message);
  }
});

test('findAttribution passes people whose name or login starts with a vendor word', () => {
  for (const [authorName, authorEmail] of [
    ['Claude Dupont', 'claude.dupont@example.fr'],
    ['Gemini Rao', 'g@example.in'],
    ['claudette', '1234+claudette@users.noreply.github.com'],
    ['Pat', '99+codexter@users.noreply.github.com'],
    ['Copilot Fan', '5+copilotfan@users.noreply.github.com'],
  ]) {
    assert.deepEqual(findAttribution({ authorName, authorEmail }), [], `${authorName} <${authorEmail}>`);
  }
  assert.deepEqual(findAttribution({ message: 'fix\n\nCo-authored-by: Claude Dupont <claude.dupont@example.fr>' }), []);
});

test('findAttribution passes bots that are not models', () => {
  for (const [name, email] of [
    ['dependabot[bot]', '49699333+dependabot[bot]@users.noreply.github.com'],
    ['github-actions[bot]', '41898282+github-actions[bot]@users.noreply.github.com'],
    ['GitHub', 'noreply@github.com'],
  ]) {
    assert.deepEqual(findAttribution({ authorName: name, authorEmail: email, committerName: name, committerEmail: email }), []);
  }
});

test('findAttribution flags trailers and model ids in the message', () => {
  const message = 'fix: thing\n\nCo-Authored-By: Claude Opus <noreply@example.com>\nClaude-Session: https://x\n';
  assert.equal(findAttribution({ message }).length, 2);
  assert.equal(findAttribution({ message: 'Generated with [Claude Code](https://x)' }).length, 1);
  assert.equal(findAttribution({ message: 'tested on claude-sonnet-5' }).length, 1);
});

test('findAttribution passes the owner identity and ordinary mentions of Claude', () => {
  assert.deepEqual(findAttribution({
    authorName: 'askalf', authorEmail: '263217947+askalf@users.noreply.github.com',
    committerName: 'Thomas Sprayberry', committerEmail: '263217947+askalf@users.noreply.github.com',
    message: 'docs: the MCP endpoint works with Claude Desktop\n\nCo-Authored-By: Someone <a@b.c>',
  }), []);
});

// Runs the CLI in a throwaway repo, so each mode is checked end to end and
// each failure is pinned to the check that fired.
function withRepo(fn) {
  const dir = mkdtempSync(join(tmpdir(), 'hygiene-'));
  const owner = { GIT_AUTHOR_NAME: 'askalf', GIT_AUTHOR_EMAIL: 'o@users.noreply.github.com', GIT_COMMITTER_NAME: 'askalf', GIT_COMMITTER_EMAIL: 'o@users.noreply.github.com' };
  const model = { GIT_AUTHOR_NAME: 'Claude', GIT_AUTHOR_EMAIL: 'noreply@anthropic.com' };
  const git = (args, env = {}) => execFileSync('git', args, { cwd: dir, encoding: 'utf8', env: { ...process.env, ...owner, ...env } });
  const cli = (args, env = {}) => {
    try {
      execFileSync(process.execPath, [script, ...args], { cwd: dir, stdio: 'pipe', env: { ...process.env, ...owner, ...env } });
      return { status: 0, err: '' };
    } catch (e) { return { status: e.status, err: String(e.stderr) }; }
  };
  const write = (text) => writeFileSync(join(dir, 'a.md'), text);
  try {
    git(['init', '-q', '-b', 'main']);
    write('base\n');
    git(['add', '.']); git(['commit', '-qm', 'base']);
    fn({ dir, git, cli, write, model });
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

test('--range passes a clean commit and pins each failure to its check', () => {
  withRepo(({ git, cli, write, model }) => {
    write('base\nclean\n'); git(['commit', '-qam', 'clean']);
    assert.equal(cli(['--range', 'HEAD~1..HEAD']).status, 0);

    write('base\nclean\nby a model\n'); git(['commit', '-qam', 'model'], model);
    let r = cli(['--range', 'HEAD~1..HEAD']);
    assert.equal(r.status, 1);
    assert.match(r.err, /author is Claude <noreply@anthropic\.com>/);
    assert.doesNotMatch(r.err, /em dash/);

    write(`base\nclean\nby a model\nbad ${D} line\n`); git(['commit', '-qam', 'dash']);
    r = cli(['--range', 'HEAD~1..HEAD']);
    assert.equal(r.status, 1);
    assert.match(r.err, /a\.md:4: em dash in added text/);
    assert.doesNotMatch(r.err, /author is/);
  });
});

test('--staged checks only what is staged', () => {
  withRepo(({ git, cli, write }) => {
    write(`base\nnew ${D} line\n`);
    assert.equal(cli(['--staged']).status, 0, 'unstaged change is not checked');
    git(['add', 'a.md']);
    const r = cli(['--staged']);
    assert.equal(r.status, 1);
    assert.match(r.err, /a\.md:2: em dash/);
  });
});

test('--commit-msg checks the message and the identity git will commit as', () => {
  withRepo(({ dir, git, cli, model }) => {
    const msg = join(dir, 'MSG');
    // git sets GIT_EDITOR=: for the hook when no editor opens (-m, -F, --no-edit).
    const noEditor = { GIT_EDITOR: ':' };
    const editor = { GIT_EDITOR: 'vi' };
    writeFileSync(msg, 'fix: a thing\n\n# a comment line git strips\n');
    assert.equal(cli(['--commit-msg', msg], editor).status, 0);
    let r = cli(['--commit-msg', msg], { ...editor, ...model });
    assert.equal(r.status, 1);
    assert.match(r.err, /author is Claude/);
    writeFileSync(msg, 'fix\n\nCo-Authored-By: ChatGPT <noreply@openai.com>\n');
    r = cli(['--commit-msg', msg], noEditor);
    assert.equal(r.status, 1);
    assert.match(r.err, /Co-Authored-By: ChatGPT/);
    writeFileSync(msg, `fix ${D} thing\n`);
    assert.match(cli(['--commit-msg', msg], noEditor).err, /em dash/);

    // Without an editor git keeps # lines, so they are checked, a bare # included.
    writeFileSync(msg, `#113 fix ${D} thing\n`);
    assert.match(cli(['--commit-msg', msg], noEditor).err, /em dash/);
    writeFileSync(msg, 'fix\n#\n# Co-Authored-By: ChatGPT <noreply@openai.com>\n');
    assert.match(cli(['--commit-msg', msg], noEditor).err, /Co-Authored-By: ChatGPT/);

    // With an editor git strips # lines, so its template is not checked, in any locale.
    const template = (lines) => ['fix: clean message', '', ...lines, ''].join('\n');
    writeFileSync(msg, template([
      '# Please enter the commit message for your changes. Lines starting',
      "# with '#' will be ignored, and an empty message aborts the commit.",
      '#', '# On branch gpt-5-migration', '#\tnew file:   gemini-2.5-pro.json', '#',
    ]));
    assert.equal(cli(['--commit-msg', msg], editor).status, 0);
    writeFileSync(msg, template([
      '# Bitte geben Sie eine Commit-Beschreibung f\u00fcr Ihre \u00c4nderungen ein.',
      '#', '# Auf Branch gpt-5-migration', '#\tneue Datei:   gemini-2.5-pro.json', '#',
    ]));
    assert.equal(cli(['--commit-msg', msg], editor).status, 0);

    // Under a non-strip cleanup mode git keeps # lines even with an editor.
    writeFileSync(msg, `fix\n# kept ${D} line\n`);
    git(['config', 'commit.cleanup', 'verbatim']);
    assert.match(cli(['--commit-msg', msg], editor).err, /em dash/);
    git(['config', 'commit.cleanup', 'strip']);
    assert.equal(cli(['--commit-msg', msg], noEditor).status, 0, 'cleanup=strip drops # lines without an editor too');
    git(['config', '--unset', 'commit.cleanup']);
    assert.equal(cli(['--commit-msg', msg], editor).status, 0);

    // core.commentChar decides which lines are comments.
    git(['config', 'core.commentChar', ';']);
    writeFileSync(msg, template([';', '; On branch gpt-5-migration', ';']));
    assert.equal(cli(['--commit-msg', msg], editor).status, 0);
    writeFileSync(msg, `#113 fix ${D} thing\n`);
    assert.match(cli(['--commit-msg', msg], editor).err, /em dash/, '# is not a comment then');
    git(['config', '--unset', 'core.commentChar']);

    // commit -v: everything from the scissors line on is the diff, not the message.
    writeFileSync(msg, [
      'fix: clean message', '',
      '# ------------------------ >8 ------------------------',
      '# Do not modify or remove the line above.',
      'diff --git a/a.md b/a.md', ` a ${D} b`, '+tested on claude-sonnet-5', '',
    ].join('\n'));
    assert.equal(cli(['--commit-msg', msg], editor).status, 0);
    assert.equal(cli(['--commit-msg', msg], noEditor).status, 0);
  });
});

test('findBodyProblems flags a generator footer, a session link and an em dash', () => {
  const body = `## Summary\n\nA ${D} B\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_x)_`;
  assert.deepEqual(findBodyProblems(body), [
    'message contains "claude.ai/code/session_x"',
    'message contains "Generated by [Claude Code"',
    'contains an em dash',
  ]);
  assert.deepEqual(findBodyProblems('## Summary\n\nWorks with Claude Desktop.'), []);
  // Describing the check is not a session link.
  assert.deepEqual(findBodyProblems('- `--pr-body` flags a claude.ai/code session link'), []);
});
